#FROM openjdk:17-jre-slim
FROM amazoncorretto:17-alpine

ENV JAVA_OPTS " -Xms512m -Xms512m -Djava.security.edg=file:/dev/./urandom"

EXPOSE 8080

WORKDIR application

COPY target/bank-api-0.0.2-SNAPSHOT.jar ./

ENTRYPOINT ["java", "-jar","bank-api-0.0.2-SNAPSHOT.jar"]