name: AzureSpringCloud
on: push
env:
  ASC_PACKAGE_PATH: ${{ github.workspace }}
  JAVA_VERSION: 17
  AZURE_SUBSCRIPTION: 4fcfa6a1-71ea-4f26-a19d-61bac9614ad4

jobs:
  deploy_to_production:
    runs-on: ubuntu-latest
    name: deploy to production with artifact
    steps:
      - name: Checkout Github Action
        uses: actions/checkout@v2
        
      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}

      - name: maven build, clean
        run: |
          mvn clean package -DskipTests
      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: deploy to production step with soruce code
        uses: azure/spring-apps-deploy@v1
        with:
          azure-subscription: ${{ env.AZURE_SUBSCRIPTION }}
          action: deploy
          service-name: test-azure-app
          app-name: test-application
          use-staging-deployment: false
          package: ${{ env.ASC_PACKAGE_PATH }}
#      - name: deploy to production with artifact
#        uses: azure/spring-apps-deploy@v1
#        with:
#          azure-subscription: ${{ env.AZURE_SUBSCRIPTION }}
#          action: Deploy
#          service-name: test-azure-app
#          app-name: test-application
#          use-staging-deployment: false
#          package: ${{ env.ASC_PACKAGE_PATH }}/**/*.jar
